# Generated by Django 4.0.3 on 2022-04-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='null', max_length=256)),
                ('text', models.CharField(default='null', max_length=256)),
            ],
        ),
    ]
